### ISSUE TITLE
Consumir api Via CEP

### ISSUE THREAD

**Issue by GuiHSM** [Luanftg/codigo-do-futuro-api-dotnet#48]
### 48 - Consumir api Via CEP

Hoje em dia não conseguimos achar o restante do endereço apenas colocando o CEP, auxiliaria no cadastro de clientes e produtos se isso acontecesse

- [x] Estudar API Via CEP
- [x] Implementar API Via CEP

**Comment by bruno-esilva** [comment]
Consumo feito à partir do package cep-promisse.
